# Generated by Django 4.2.3 on 2023-10-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='minimum_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
